---
title: "Dissertation"
author: "Niansheng Niu"
date: "10/11/2021"
output: html_document
---

```{r}
library(dplyr)
library(tidyverse)
library(here)
library(magrittr)
library(sf)
library(tmap)
library(janitor)
library(spdep)
library(RColorBrewer)
library(tmap)
library(spgwr)
library(sp)
library(rgdal)
library(rgeos)
library(tmap)
library(osmdata)
library(raster)
library(rosm)
library(dbscan)
library(leaflet)
library(maptools)
library(sp)
library(adehabitatHR)
library(tmaptools)
library(shiny)
library(spatstat)
```



```{r}
price4 <- read.csv("resale-flat-prices-based-on-registration-date-from-jan-2017-onwards.csv")
price3 <- read.csv("resale-flat-prices-based-on-registration-date-from-jan-2015-to-dec-2016.csv")
price2 <- read.csv("resale-flat-prices-based-on-registration-date-from-mar-2012-to-dec-2014.csv")
```

```{r}
price2012 <- price2 %>% filter(month == "2012-03" | month == "2012-04" | month == "2012-05" | month == "2012-06" | month == "2012-07" | month == "2012-08" | month == "2012-09" 
                               | month == "2012-10" | month == "2012-11" | month == "2012-12")

price2013 <- price2 %>% filter(month == "2013-01" | month == "2013-02" | month == "2013-03" | month == "2013-04" | month == "2013-05" | month == "2013-06" | month == "2013-07" 
                               | month == "2013-08" | month == "2013-09" | month == "2013-10" | month == "2013-11" | month == "2013-12")
                            

price2014 <- price2 %>% filter(month == "2014-01" | month == "2014-02" | month == "2014-03" | month == "2014-04" | month == "2014-05" | month == "2014-06" | month == "2014-07" 
                               | month == "2014-08" | month == "2014-09" | month == "2014-10" | month == "2014-11" | month == "2014-12")
```

```{r}
price2012$remaining_lease = (99 - (2012 - price2012$lease_commence_date))
price2013$remaining_lease = (99 - (2013 - price2013$lease_commence_date))
price2014$remaining_lease = (99 - (2014 - price2014$lease_commence_date))
price2_final <- rbind(price2012, price2013, price2014)

housing_price <- rbind(price4, price3)
housing_price_final <- rbind(housing_price, price2_final)

housing_price_final$add <- paste("Block", housing_price_final$block, housing_price_final$street_name, "Singapore")

housing_price_final$name <- paste("Block", housing_price_final$block, housing_price_final$street_name, "Singapore", housing_price_final$storey_range, housing_price_final$floor_area_sqm)

data <- arrange(housing_price_final, month)

```


```{r}
data$storey_range <- factor(data$storey_range)
data$flat_model <- factor(data$flat_model)
data$flat_type <- factor(data$flat_type)


flat_models <- data.frame(
  "flat_model" = names(table(data$flat_model)),
  "total" = as.numeric(table(data$flat_model)),
  check.names = FALSE
)

flat_models <- flat_models[order(flat_models$total, decreasing = TRUE), ]
rownames(flat_models) <- NULL
kable(flat_models)

```
```{r}
flat_types <- data.frame(
  "flat_type" = names(table(data$flat_type)),
  "total" = as.numeric(table(data$flat_type))
)
kable(flat_types)
```



write.csv(data, "housing_price_2012-2021.csv")


df <- subset(housing_price_final, duplicated(add))

```

