# In this Rmd, I performed geocoding to hospital addresses in Singapore

# Packages
```{r}
library(ggmap)
library(dplyr)
```

# Load in the data and inspect
```{r}
hospital <- read.csv("hospital_sg.csv")
head(hospital)
```

# Add new column for full address with postal code
```{r}
hospital$full_add <- paste(hospital$postal_code, "Singapore")
```

# Geocoding for coordinates data
```{r}
register_google(key = "") # Input google API
all_add <- as.data.frame(unique(hospital$full_add))
table(hospital$full_add)
```

```{r}
all_latlon <- data.frame()
for (i in all_add){
  append_data <- data.frame(
    add = i,
    geocode(i, source = "google")
  )
  all_latlon <- rbind(all_latlon, append_data)
}

```

# merge hospital dataframe with coordinate data frame 
```{r}
hospital_final <- left_join(hospital, all_latlon, by = c("full_add" = "add"))
```


# export
```{r}
write.csv(hospital_final, file = "hospital_final.csv")
```


# Inspect geocoded hospital coordinates for accuracy
```{r}
PA <- read_sf("PA")
```

```{r}
pp <- hospital_final %>% dplyr::select(lon,lat) %>%
  st_as_sf(coords = c("lon","lat"), crs = 4236)

tm_shape(PA) + tm_polygons(col = "white", border.alpha = 0.5) +
  tm_shape(pp) + tm_dots(col = "red", size = 0.4, alpha = 0.5)
```




